<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNztzlQD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNztzlQD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNztzlQD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNztzlQD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNztzlQD\App_KernelDevDebugContainer([
    'container.build_hash' => 'NztzlQD',
    'container.build_id' => '92e10d6e',
    'container.build_time' => 1694694366,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNztzlQD');
