<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS5M1Drl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS5M1Drl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerS5M1Drl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerS5M1Drl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerS5M1Drl\App_KernelDevDebugContainer([
    'container.build_hash' => 'S5M1Drl',
    'container.build_id' => 'aa25f6aa',
    'container.build_time' => 1694677041,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS5M1Drl');
