<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLjbnU2u\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLjbnU2u/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLjbnU2u.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLjbnU2u\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLjbnU2u\App_KernelDevDebugContainer([
    'container.build_hash' => 'LjbnU2u',
    'container.build_id' => '7d1deb66',
    'container.build_time' => 1694761701,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLjbnU2u');
